//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntityEntities1 : DbContext
    {
        public DbCvEntityEntities1()
            : base("name=DbCvEntityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUTME> ABOUTME { get; set; }
        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<CONTACT> CONTACT { get; set; }
        public virtual DbSet<MYWORKS> MYWORKS { get; set; }
        public virtual DbSet<SKILLS> SKILLS { get; set; }
        public virtual DbSet<ADMIN> ADMIN { get; set; }
    }
}
